#!/usr/bin/env bash

# A thin wrapper around maim that defaults to saving screenshots in a more
# convenient directory than the home folder.

SCROT_DIR="$HOME/Pictures/scrots"

if [ ! -d "$SCROT_DIR" ]; then
    mkdir -p "$SCROT_DIR"
fi

OLD_DIR="$(pwd)"

cd "$SCROT_DIR"
maim "$@"
cd "$OLD_DIR" 
