#!/usr/bin/env bash

# This might differ from kumpooter 2 kumpooter
WIFI_PREFIX="wlp6s0"
POINTS="$(ls /etc/netctl | grep "wlp6s0")"
CURRENT="${WIFI_PREFIX}-$(echo "$(iwgetid -r)" | sed 's/ /-/g')"

select ACCESS_POINT in $POINTS; do
    # Stop the current one
    sudo netctl stop "$CURRENT"

    # Connect to the chosen one
    sudo netctl start "$ACCESS_POINT"
    exit 0
done

